name: Continuous Deployment

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
        steps:
        - uses: actions/checkout@v4.1.7
        - uses: coursier/cache-action@v6.4.6
        - uses: VirtusLab/scala-cli-setup@v1.5.0
          with:
              scala-cli-version: 1.5.0
              jvm: 'graalvm-community:22.0.2'
              power: true
        - name: Test
          run: scala-cli test .
        - name: Package
          run: scala-cli .github/scripts/package.sc
        - name: Publish
          uses: actions/upload-artifact@v4.4.0
          with:
            name: launchers
            path: artifacts
            if-no-files-found: error
            retention-days: 7
            overwrite: true
